import { MyContextProvider } from "@/store/MyContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <MyContextProvider>
        <body>{children}</body>
      </MyContextProvider>
    </html>
  );
}
