import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MyContextProvider } from "@/store/MyContext";
import "tailwindcss/tailwind.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Threads INN",
  description: "Generated by ThreadsINN Team",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <MyContextProvider>
        <body>{children}</body>
      </MyContextProvider>
    </html>
  );
}
